# Site settings
title: OSXBricks Articles Backup
email: contact@osxbricks.com
description: "This is a backup of articles on http://osxbricks.com."
baseurl: ""
url: "http://leolelego.github.io/osxbricks/"
twitter_username: osxbricks
github_username:  leolelego

# Build settings
markdown: kramdown
permalink: pretty
