# Site settings
title: OSXBricks
email: contact@osxbricks.com
description: "Some bricks for your code and your OS X"
baseurl: ""
url: # "http://leolelego.github.io/osxbricks/"
copyright:Copyright © 2014 Léo Derbois and OSXBricks. All rights reserved.



# Site
metadata: ["OS X BRicks","OSXBricks","OS X","Xcode","server","CV","Boba Fett"] # Metadata for 
googleAnalyticsID: UA-52933969-1
favicon         : /assets/favicon.ico 		# website Favicon  / Need to be local (in assets forlder)


# account
twitter: leoderbois
github: leoderbois 
linkedin: leoderbois
feedUrl : http://feed.com
resume_site: http://www.leoderbois.com
author_page: author 

# Build settings
markdown: kramdown
permalink: /:title
