# Site settings
title: OSXBricks Light
email: contact@osxbricks.com
description: "Version allégé du site "
baseurl: "/osxbricks/"
url: "http://leolelego.github.io/osxbricks/"
twitter_username: osxbricks
github_username:  leoderbois

# Build settings
markdown: kramdown
permalink: pretty
