# Site settings
title: OSXBricks
email: contact@osxbricks.com
<<<<<<< HEAD
description: "Some bricks for your code and your OS X"
baseurl: ""
url: # "http://leolelego.github.io/osxbricks/"



# Site
metadata: ["OS X BRicks","OSXBricks","OS X","Xcode","server","CV","Boba Fett"] # Metadata for 
googleAnalyticsID: UA-52933969-1
favicon         : /assets/favicon.ico 		# website Favicon  / Need to be local (in assets forlder)


# account
twitter: leoderbois
github: leoderbois 
linkedin: leoderbois

=======
description: "Version allégé du site "
baseurl: ""
url: "http://jekyll.osxbricks.com"
twitter_username: osxbricks
github_username:  leoderbois
>>>>>>> FETCH_HEAD

# Build settings
markdown: kramdown
permalink: /:title
