# Site settings
title: OSXBricks
email: contact@leoderbois.com
description: "This is a backup of articles on http://osxbricks.com."
baseurl: "http://leolelego.github.io/osxbricks/"
url: "http://leolelego.github.io/osxbricks/"
twitter_username: osxbricks
github_username:  leolelego

# Build settings
markdown: kramdown
permalink: pretty
