# Site settings
title: OSXBricks Light
email: contact@osxbricks.com
description: "This is a lighter version the site http://osxbricks.com."
baseurl: "/osxbricks/"
url: "http://leolelego.github.io/osxbricks/"
twitter_username: osxbricks
github_username:  leolelego

# Build settings
markdown: kramdown
permalink: pretty
